import 'package:flutter_application_1/Models/Product.dart';

class ImageAutoScrolle {
  static final List<String> offerImage = [
    'assets/images/offerImg1.jpg',
    'assets/images/offerImg2.jpg',
    'assets/images/offerImg3.jpg',
    'assets/images/offerImg4.jpg',
    'assets/images/offerImg5.jpg',
  ];
  static final List<String> vipImage = [
    'assets/images/vipImg1.png',
    'assets/images/vipImg2.jpg',
    'assets/images/vipImg3.png',
    'assets/images/vipImg5.jpg',
    'assets/images/vipImg4.jpg',
  ];

  static final List<ProductModel> productsList = [
    ProductModel(
      id: 'Apricot',
      title: 'Apricot',
      prix: 0.99,
      solde: 0.49,
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      isOnSolde: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Avocado',
      title: 'Avocado',
      prix: 0.88,
      solde: 0.5,
      imageUrl: 'https://i.ibb.co/9VKXw5L/Avocat.png',
      productCategoryName: 'Fruits',
      isOnSolde: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Black grapes',
      title: 'Black grapes',
      prix: 1.22,
      solde: 0.7,
      imageUrl: 'https://i.ibb.co/c6w5zrC/Black-Grapes-PNG-Photos.png',
      productCategoryName: 'Fruits',
      isOnSolde: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Fresh_green_grape',
      title: 'Fresh green grape',
      prix: 1.5,
      solde: 0.5,
      imageUrl: 'https://i.ibb.co/HKx2bsp/Fresh-green-grape.png',
      productCategoryName: 'Fruits',
      isOnSolde: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Green grape',
      title: 'Green grape',
      prix: 0.99,
      solde: 0.4,
      imageUrl: 'https://i.ibb.co/bHKtc33/grape-green.png',
      productCategoryName: 'Fruits',
      isOnSolde: false,
      isPiece: false,
    ),
    ProductModel(
      id: 'Red apple',
      title: 'Red apple',
      prix: 0.6,
      solde: 0.2,
      imageUrl: 'https://i.ibb.co/crwwSG2/red-apple.png',
      productCategoryName: 'Fruits',
      isOnSolde: true,
      isPiece: false,
    ),
    // Vegi
    ProductModel(
      id: 'Carottes',
      title: 'Carottes',
      prix: 0.99,
      solde: 0.5,
      imageUrl: 'https://i.ibb.co/TRbNL3c/Carottes.png',
      productCategoryName: 'Vegetables',
      isOnSolde: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Cauliflower',
      title: 'Cauliflower',
      prix: 1.99,
      solde: 0.99,
      imageUrl: 'https://i.ibb.co/xGWf2rH/Cauliflower.png',
      productCategoryName: 'Vegetables',
      isOnSolde: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Cucumber',
      title: 'Cucumber',
      prix: 0.99,
      solde: 0.5,
      imageUrl: 'https://i.ibb.co/kDL5GKg/cucumbers.png',
      productCategoryName: 'Vegetables',
      isOnSolde: false,
      isPiece: false,
    ),
    ProductModel(
      id: 'Jalape',
      title: 'Jalape',
      prix: 1.99,
      solde: 0.89,
      imageUrl: 'https://i.ibb.co/Dtk1YP8/Jalape-o.png',
      productCategoryName: 'Vegetables',
      isOnSolde: false,
      isPiece: false,
    ),
    ProductModel(
      id: 'Long yam',
      title: 'Long yam',
      prix: 2.99,
      solde: 1.59,
      imageUrl: 'https://i.ibb.co/V3MbcST/Long-yam.png',
      productCategoryName: 'Vegetables',
      isOnSolde: false,
      isPiece: false,
    ),
    ProductModel(
      id: 'Onions',
      title: 'Onions',
      prix: 0.59,
      solde: 0.28,
      imageUrl: 'https://i.ibb.co/GFvm1Zd/Onions.png',
      productCategoryName: 'Vegetables',
      isOnSolde: false,
      isPiece: false,
    ),
    ProductModel(
      id: 'Plantain-flower',
      title: 'Plantain-flower',
      prix: 0.99,
      solde: 0.389,
      imageUrl: 'https://i.ibb.co/RBdq0PD/Plantain-flower.png',
      productCategoryName: 'Vegetables',
      isOnSolde: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Potato',
      title: 'Potato',
      prix: 0.99,
      solde: 0.59,
      imageUrl: 'https://i.ibb.co/wRgtW55/Potato.png',
      productCategoryName: 'Vegetables',
      isOnSolde: true,
      isPiece: false,
    ),
    ProductModel(
      id: 'Radish',
      title: 'Radish',
      prix: 0.99,
      solde: 0.79,
      imageUrl: 'https://i.ibb.co/YcN4ZsD/Radish.png',
      productCategoryName: 'Vegetables',
      isOnSolde: false,
      isPiece: false,
    ),
    ProductModel(
      id: 'Red peppers',
      title: 'Red peppers',
      prix: 0.99,
      solde: 0.57,
      imageUrl: 'https://i.ibb.co/JthGdkh/Red-peppers.png',
      productCategoryName: 'Vegetables',
      isOnSolde: false,
      isPiece: false,
    ),
    ProductModel(
      id: 'Squash',
      title: 'Squash',
      prix: 3.99,
      solde: 2.99,
      imageUrl: 'https://i.ibb.co/p1V8sq9/Squash.png',
      productCategoryName: 'Vegetables',
      isOnSolde: true,
      isPiece: true,
    ),
    ProductModel(
      id: 'Tomatoes',
      title: 'Tomatoes',
      prix: 0.99,
      solde: 0.39,
      imageUrl: 'https://i.ibb.co/PcP9xfK/Tomatoes.png',
      productCategoryName: 'Vegetables',
      isOnSolde: true,
      isPiece: false,
    ),
    // Grains
    ProductModel(
      id: 'Corn-cobs',
      title: 'Corn-cobs',
      prix: 0.29,
      solde: 0.19,
      imageUrl: 'https://i.ibb.co/8PhwVYZ/corn-cobs.png',
      productCategoryName: 'Grains',
      isOnSolde: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Peas',
      title: 'Peas',
      prix: 0.99,
      solde: 0.49,
      imageUrl: 'https://i.ibb.co/7GHM7Dp/peas.png',
      productCategoryName: 'Grains',
      isOnSolde: false,
      isPiece: false,
    ),
    // Herbs
    ProductModel(
      id: 'Asparagus',
      title: 'Asparagus',
      prix: 6.99,
      solde: 4.99,
      imageUrl: 'https://i.ibb.co/RYRvx3W/Asparagus.png',
      productCategoryName: 'Herbs',
      isOnSolde: false,
      isPiece: false,
    ),
    ProductModel(
      id: 'Brokoli',
      title: 'Brokoli',
      prix: 0.99,
      solde: 0.89,
      imageUrl: 'https://i.ibb.co/KXTtrYB/Brokoli.png',
      productCategoryName: 'Herbs',
      isOnSolde: true,
      isPiece: true,
    ),
    ProductModel(
      id: 'Buk-choy',
      title: 'Buk-choy',
      prix: 1.99,
      solde: 0.99,
      imageUrl: 'https://i.ibb.co/MNDxNnm/Buk-choy.png',
      productCategoryName: 'Herbs',
      isOnSolde: true,
      isPiece: true,
    ),
    ProductModel(
      id: 'Chinese-cabbage-wombok',
      title: 'Chinese-cabbage-wombok',
      prix: 0.99,
      solde: 0.5,
      imageUrl: 'https://i.ibb.co/7yzjHVy/Chinese-cabbage-wombok.png',
      productCategoryName: 'Herbs',
      isOnSolde: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Kangkong',
      title: 'Kangkong',
      prix: 0.99,
      solde: 0.5,
      imageUrl: 'https://i.ibb.co/HDSrR2Y/Kangkong.png',
      productCategoryName: 'Herbs',
      isOnSolde: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Leek',
      title: 'Leek',
      prix: 0.99,
      solde: 0.5,
      imageUrl: 'https://i.ibb.co/Pwhqkh6/Leek.png',
      productCategoryName: 'Herbs',
      isOnSolde: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Spinach',
      title: 'Spinach',
      prix: 0.89,
      solde: 0.59,
      imageUrl: 'https://i.ibb.co/bbjvgcD/Spinach.png',
      productCategoryName: 'Herbs',
      isOnSolde: true,
      isPiece: true,
    ),
    ProductModel(
      id: 'Almond',
      title: 'Almond',
      prix: 8.99,
      solde: 6.5,
      imageUrl: 'https://i.ibb.co/c8QtSr2/almand.jpg',
      productCategoryName: 'Nuts',
      isOnSolde: true,
      isPiece: false,
    ),
  ];
}